<%@ Page Title="Devolucion" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Devolucion.aspx.cs" Inherits="Pañol.Devolucion" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
   <br />
 <form action="">
 <div class="form-group">
       <div class="row">
        <div class="col-md-6">
             <h1><span class="label label-default">Devolucion de articulos</span></h1>
    <table style="width: 100%;">
        <tr>
            <td style="height: 22px; width: 409px"><asp:Label ID="Label1" runat="server" Text="Tarjeta:"></asp:Label>
                <br/><asp:TextBox ID="txtTarjeta" runat="server" Height="27px" Width="206px" onkeypress="javascript:return solonumeros(event)" ></asp:TextBox>
                 <ajaxToolkit:AutoCompleteExtender 
                     ID="txtTarjeta_AutoCompleteExtender" 
                     runat="server" 
                        Enabled="true"
                       TargetControlID="txtTarjeta"
                       MinimumPrefixLength="1"
                       ServiceMethod="ObtenerTarjetasAct" 
                      ServicePath="~/WSArticulos.asmx"
                      EnableCaching="true"
                     UseContextKey="true"
                     FirstRowSelected="true"
                     CompletionSetCount="10"
                    CompletionInterval="0">
                </ajaxToolkit:AutoCompleteExtender>
                 <asp:Button ID="btnSeleccionar" runat="server" Text="Seleccionar"  cssclass="btn btn-primary btn-s" OnClick="btnSeleccionar_Click"/>
            </td>
             <td style="height: 22px">&nbsp;</td>
            
            
        </tr>
      </table>
            <asp:Panel ID="pObservacion" runat="server">
        <table>
         <tr>
           
            <td style="height: 22px; width: 176px"><asp:Label ID="Label4" runat="server" Text="Observacion:"></asp:Label><br />
                <asp:TextBox ID="txtObservacion" runat="server" Height="187px" Width="352px" TextMode="MultiLine" MaxLength="200"></asp:TextBox></td>
            <td style="height: 22px">&nbsp;</td>
           
        </tr>
  
    </table>

     <br />
     <asp:Button ID="btnDevolucion" runat="server" Text="Confirmar Devolucion" CssClass="btn btn-primary btn-lg" OnClick="btnDevolucion_Click"/>
 <a href="Default.aspx" class="btn btn-secondary btn-lg">Cancelar </a>
 </asp:Panel>
</div>
  <div class="col-md-6">
      <asp:Panel ID="pLista" runat="server">

          <asp:GridView ID="gvPedido" runat="server" CssClass="table table-striped table-hover table-condensed small-top-margin" AutoGenerateDeleteButton="True" Caption="Lista de articulos pendientes de devolucion:" OnRowDeleting="gvPedido_RowDeleting" EmptyDataText="No se encuentran articulos pendientes de devolucion." ></asp:GridView>
          <asp:GridView ID="gvDevolucion" runat="server" CssClass="table table-striped table-hover table-condensed small-top-margin" Caption="Lista de articulos ingresados:" EmptyDataText="No se encuentran articulos ingresados."></asp:GridView>
          <asp:Button ID="btnCancelar" class="btn btn-warning btn-s" runat="server" Text="Cancelar" OnClick="btnCancelar_Click" />
      </asp:Panel>


   </div>
</div>
</div>
</form>
    <script>
    function solonumeros(e) {

            var key;

            if (window.event) // IE
            {
        key = e.keyCode;
            }
            else if (e.which) // Netscape/Firefox/Opera
            {
        key = e.which;
            }

            if (key < 48 || key > 57) {
                return false;
            }

            return true;
        }

    </script>
</asp:Content>
